### ISSUE TITLE
로그인 유저 상태 관리

### ISSUE THREAD

**Issue by nujeyh** [nujeyh/react-outstagram#1]
안녕하세요!! 로그인 유저 상태 관리 하는 법에 대해 질문이 있습니다!!

일단 어떤 사용자가 로그인한 건지 알고 싶어서
App.js 에서 파이어 베이스가 로그인 유저 정보를 보내주면
이메일로 닉네임을 받아와서 리덕스에 저장하고, 필요할 때(수정/삭제 접근할 때, 글작성할 때...) 
꺼내쓰는 방식을 사용했는데요!! (인증 단 한 번만 하는 방식)
이것이 적절한 관리 방법이었는지 궁금합니다!!

> 제가 생각해본 방법
> 1. 메인이 렌더링될 때마다 파이어베이스랑 통신해서 로그인 정보를 계속 확인
> 2. 유저 정보가 꼭 필요한 기능들(수정 삭제)을 쓰려할 때(작성하기 버튼을 클릭할 때 등) 확인

>    터무니 없는 질문이라면 죄송합니다...🫠

```javascript
// src / components / App.js
...
useEffect(() => {
  // 파이어베이스 로그인 여부 확인
  auth.onAuthStateChanged((userAuth) => {
    if (userAuth) {
      dispatch(loadUserFB(userAuth.email));
    } else {
    }
  });
}, []);
...
```

```javascript
// src / redux / modules / userSlice.js
...
export const loadUserFB = (email) => {
  return async function (dispatch) {
    const docRef = collection(db, "users");
    const newQuery = query(docRef, where("email", "==", email));
    const userData = await getDocs(newQuery);
    userData.forEach((data) => {
      dispatch(currentUser(data.data()));
    });
  };
};

const userSlice = createSlice({
  name: "userReducer",
  initialState: { email: null, nickname: null },
  reducers: {
    currentUser: (state, { payload }) => {
      state.email = payload.email;
      state.nickname = payload.nickname;
    },
  },
});
```

**Comment by jihyunan-dev** [comment]
안녕하세요 혜준님:) 질문 및 몇가지 내용 말씀드리겠습니다.

1. 질문에 대한 답변
: 저라도 리덕스에 저장하고 사용했을 듯 합니다:) 
파이어베이스에 저장 등의 요청을 했을 때 이 로그인이 만료되었다면, 저장 대신 인증이 되지 않았다는 내용을 보내줄테니 그 때를 예외처리하는 방식으로 사용했을듯 합니다ㅎㅎ
절대 터무니 없지 않고 너무 좋은 고민이고 좋은 해결이었다고 생각합니다. 사용 중 로그인 시간이 끝났을 때의 처리만 잘 고민해주시면 될 듯합니다!

2. 각 컴포넌트의 재사용성
: 전체적으로 잘 만드셨습니다. 다만 몇 가지 고민하실 점만 말씀드리려고 합니다. 
- 1) App.js 와 displayedAt.js 는 components 디렉토리에 존재하는 것이 맞을지?
- 2) Post.js에서 layout 세가지를 구분하기 위해 return 문 안에서 객체를 만들고 `postObj.layout` 을 key로 하여 가져왔는데, 접근 방식은 굉장히 좋으나 더 깔끔하게 작성할 수 있을 방법은 업을지. (`return`문 내에서 복잡한 공식을 작성하게 되면 어떤게 렌더되는지 한 눈에 파악이 어렵습니다. => 유지보수가 힘들어집니다. 같은 방식이라도 더 읽기 편하게 작성하는 방법을 고민해보시면 좋을듯합니다.)

3. 상태관리(데이터 fetch 포함)
: 마찬가지로 잘 하셨습니다. 여기서도 고민할 점 하나만 짚어드립니다.
- 현재 App.js에서 모든 포스트를 가져오는 것으로 보입니다. 
```javascript
    useEffect(() => {
        dispatch(loadPostFB());
    }, []);
```
디테일 페이지에 가서도 가져왔던 포스트 리스트 중에서 해당 데이터를 가져와서 보여주는 형태입니다. 
현재 이 구조에서는 새로고침을 하거나 어떤 행위를 해도 디테일 페이지가 잘 나오고 있습니다.
하지만 만약 총 포스트의 수가 10000개 정도 된다고 하면 어떻게 될까요?
총 포스트 수가 10000개 정도 되고, 사람들은 메인페이지를 이용하지 않고 필요한 디테일 페이지만 모아놓고 이동한다고 가정하겠습니다.
https://out5tagram.web.app/y1kCQZsVRvtKKe0xgmrm
https://out5tagram.web.app/NbbyHweAFDcGNHTlHIJP
이런 식으로요:)
그러면 각각 링크를 누를 때마다 해당 탭에서는 10000개의 포스트를 가져오게 되고, 그 중에 해당 포스트를 찾아 렌더하는 방식을 취하게 될 것으로 보입니다. 
그렇다면 위에 가정한 상황에서도 가장 빠르게 데이터를 보여줄 수 있는 동시에 불필요한 데이터를 가져오지 않는 방법은 어떤게 있을까요? 고민해보시면 좋을 것 같습니다.

한 주도 고생많으셨습니다:)
추가적으로 `/:id` 에서 해당 포스트가 없으면 404페이지를 보여주는 것도 고민해보시면 좋겠습니다!
